name: SkProtobuf
version: ${version}
main: com.github.officialdonut.skprotobuf.SkProtobuf
api-version: "1.21.4"
depend: [Skript]

permissions:
  skprotobuf.admin:
    default: op

commands:
  skprotobuf:
    aliases: [skproto]
    permission: skprotobuf.admin